# Generated by Django 2.2 on 2020-08-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200810_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='webapp.Type', verbose_name='Тип'),
        ),
    ]
