# Generated by Django 2.2 on 2020-08-12 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_tasks_type_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='summary',
            field=models.CharField(default='My title', max_length=200, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Название'),
        ),
    ]
