# Generated by Django 2.2 on 2020-08-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20200812_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
