# Generated by Django 2.2 on 2020-08-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20200827_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='HELLO WORLD!', max_length=300, verbose_name='Название проекта'),
        ),
    ]
